"""empty message

Revision ID: 120697662d5c
Revises: f571a02ccc39
Create Date: 2019-02-11 16:05:21.486453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120697662d5c'
down_revision = 'f571a02ccc39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'events', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_column('events', 'name')
    # ### end Alembic commands ###
